Ssubject:
  name: RIDE HILLING APP GATEWAY

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
        - id: ride-service
          uri: lb://ride-service
          predicates:
            - Path=/api/rides/**

