server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userdb_test
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka
