server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://prod-host:3306/userdb
    username: prod_user
    password: secure_pass
  jpa:
    hibernate:
      ddl-auto: validate

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8763/eureka
